#!/usr/bin/env python3

# ssm-tunnel-client
# Author: Michael Ludvig

import sys
import threading
import pexpect
from base64 import b85encode, b85decode
from pytun import TunTapDevice

def setup_tun(src, dst):
    tun = TunTapDevice()

    tun.addr = src
    tun.dstaddr = dst
    tun.netmask = '255.255.255.255'
    tun.mtu = 1500

    tun.up()

    return tun

def tun_reader(tun):
    while True:
        buf = tun.read(tun.mtu)
        print("%{}".format(b85encode(buf).decode('ascii')))

def main():
    tun = setup_tun(sys.argv[1], sys.argv[2])
    print(f"# Client device {tun.name} is ready", flush=True)

    t = threading.Thread(target=tun_reader, args=(tun,))
    t.daemon = True
    t.start()

    try:
        while True:
            line = sys.stdin.readline()
            if line[0] == '%':
                buf = b85decode(line[1:].strip('\n\r'))
                tun.write(buf)

    except KeyboardInterrupt:
        tun.down()
        tun.close()

if __name__ == "__main__":
    main()
